<a href="https://colab.research.google.com/github/AR70GU/python_assignment_IIT/blob/main/python_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from types import new_class
age = input("what is your name? : ")
new_age = int(age) + 12
print(int(new_age))


what is your name? : 23
35


In [ ]:
a = int(input("enter your first value:"))
b = int(input("enter your second value:"))

sum = a + b

print("sum:" , sum)




enter your first value:120
enter your second value:240
sum: 360


In [ ]:
name = "Tony Stark"

print(name.upper())

print(name.find("kr"))

print(name.replace("rk" , "iitjammu"))

print("X" in name)



TONY STARK
-1
Tony Staiitjammu
False


In [ ]:
p1 = 99.5
p2 = 23
p3 = 123.5

print(p1 + p2 + p3)

print(p1 + p2 + p3/3)


superhero_name = input("iron man ")

print(superhero_name + " kill hulk")

246.0
163.66666666666666
iron man tony
tony kill hulk


In [ ]:
print("hello world")

name = input("hello ,what is your name ")

print(name + " what a beautiful name")



hello world
hello ,what is your name arnav gupta
arnav gupta what a beautiful name


In [ ]:
name = input("arnav_gupta")
print("hello" + name)

arnav_gupta arnav
hello arnav


In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16],
              ])

#array[start:end:step]

print(a[0:2, 0:3])
print(a[0:2, 2:4])
print(a[2:4, 2:4])

[[1 2 3]
 [5 6 7]]
[[3 4]
 [7 8]]
[[11 12]
 [15 16]]


In [ ]:
a = np.array([12,13,14,100,15,34])


print(a == 100)

[False False False  True False False]


In [ ]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])

print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))
print(np.var(a))
print(np.std(a))

print(np.sum(a,axis = 1))
print(np.sum(a,axis = 0))

55
5.5
10
1
8.25
2.8722813232690143
[15 40]
[ 7  9 11 13 15]


In [ ]:
name = input("enter your name")

print(name)


enter your namearnav gupta
arnav gupta


In [ ]:
i = int(input("guess my age(between 12 and 20) "))

if i == 17:
    print("you are right")
else:
    print("you are wrong")

    loop = True

guess my age(between 12 and 20) 20
you are wrong


In [ ]:
import random

print("hello, lets guess my room number(3055-3075): ")

secret_room_number = random.randint(3070,3070)
max_tries = 5
tries_left = max_tries
flag = False

while not flag and tries_left > 0:

     user_guess = int(input("enter your guess: "))

     if user_guess == secret_room_number:
            print("Congratulations! You are right!")
            flag = True

     else:
            print("wrong guess try again")
            tries_left -= 1


if not flag:
    print("Sorry, you ran out of tries. The secret room number was 3070.")

hello, lets guess my room number(3055-3075): 
enter your guess: 3071
wrong guess try again
enter your guess: 3072
wrong guess try again
enter your guess: 3073
wrong guess try again
enter your guess: 3074
wrong guess try again
enter your guess: 3075
wrong guess try again
Sorry, you ran out of tries. The secret room number was 3070.


In [ ]:
import turtle
